/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _IDL_H_RPCGEN
#define _IDL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data {
	u_int pid1;
	u_int pid2;
	u_int valeur;
};
typedef struct data data;


#define IDL 0x20000001
#define VERSION_UN 1

#if defined(__STDC__) || defined(__cplusplus)
#define NOTIFIER_RECEPTION 0
extern  void * notifier_reception_1(data *, CLIENT *);
extern  void * notifier_reception_1_svc(data *, struct svc_req *);
extern int idl_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define NOTIFIER_RECEPTION 0
extern  void * notifier_reception_1();
extern  void * notifier_reception_1_svc();
extern int idl_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);
extern  bool_t xdr_data (XDR *, data*);

#else /* K&R C */
extern bool_t xdr_data ();
extern bool_t xdr_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_IDL_H_RPCGEN */
