/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "IDL.h"

bool_t
xdr_data (XDR *xdrs, data *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->pid1))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->pid2))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->valeur))
		 return FALSE;
	return TRUE;
}
